#This image should be named bitcoin-alpine-bin
FROM bitcoin-alpine-build
RUN (cd bitcoin && ./autogen.sh && \
                    ./configure --disable-tests \
                    --disable-bench --disable-static \
                    --without-gui --disable-zmq \
                    --with-incompatible-bdb \
                    CFLAGS='-w' CXXFLAGS='-w' && \
                    make -j 4 && \
                    make install)